# Generated by Django 3.2.4 on 2021-06-09 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carritopro',
            fields=[
                ('idCarrito', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCat', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('idComuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombreComuna', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('idConct', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=30)),
                ('asunto', models.CharField(max_length=20)),
                ('mensaje', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idRegion', models.AutoField(primary_key=True, serialize=False)),
                ('nombreRegion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tipodocumento',
            fields=[
                ('idDoc', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tipouser',
            fields=[
                ('idTip', models.AutoField(primary_key=True, serialize=False)),
                ('clieAdmin', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('idUser', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=30)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
                ('tipodoc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tool.tipodocumento')),
                ('tipouser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tool.tipouser')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo de produto')),
                ('nombreProducto', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
                ('carritopro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.carritopro')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('idDireccion', models.AutoField(primary_key=True, serialize=False)),
                ('descDireccion', models.CharField(max_length=50)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.comuna')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.user')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.region'),
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('idCarro', models.AutoField(primary_key=True, serialize=False)),
                ('fechaCompra', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=30)),
                ('totalPago', models.IntegerField()),
                ('carritopro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tool.carritopro')),
            ],
        ),
    ]
