# Generated by Django 3.2.3 on 2021-06-02 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('idComuna', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreComuna', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('idConct', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=30)),
                ('asunto', models.CharField(max_length=20)),
                ('mensaje', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idRegion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreRegion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('idUser', models.IntegerField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=30)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='producto',
            new_name='categoria',
        ),
        migrations.AddField(
            model_name='producto',
            name='carritopro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tool.carritopro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo de produto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
        migrations.CreateModel(
            name='Tipouser',
            fields=[
                ('idTip', models.IntegerField(primary_key=True, serialize=False)),
                ('clieAdmin', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.user')),
            ],
        ),
        migrations.CreateModel(
            name='Tipodocumento',
            fields=[
                ('numDoc', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.user')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('idDireccion', models.IntegerField(primary_key=True, serialize=False)),
                ('descDireccion', models.CharField(max_length=50)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.comuna')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.user')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.region'),
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('idCarro', models.IntegerField(primary_key=True, serialize=False)),
                ('fechaCompra', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=30)),
                ('totalPago', models.IntegerField()),
                ('carritopro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.carritopro')),
            ],
        ),
    ]
