# Generated by Django 3.2.3 on 2021-06-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_usuario_numdoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numdoc',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
