# Generated by Django 3.2.3 on 2021-06-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0004_alter_usuario_numdoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='mensaje',
            field=models.CharField(max_length=500),
        ),
    ]
